#!/bin/bash
set -e -x

DOCKER_VERSION=${DOCKER_VERSION:-$1}
if [ "$DOCKER_VERSION" == "" ]; then
  echo "DOCKER_VERSION unset"
  exit
fi

echo "looking at $DOCKER_VERSION"
# detect arch
fileinfo=$(file bundles/${DOCKER_VERSION}/binary-daemon/docker-containerd)
echo "$fileinfo"
if grep 32-bit <<<$fileinfo ; then
  if grep ARM <<<$fileinfo ; then
    ARCH='arm'
  fi
fi
if grep 64-bit <<<$fileinfo ; then
  if grep ARM <<<$fileinfo ; then
    ARCH='arm64'
  fi
fi

mkdir -p dist/docker
cp bundles/${DOCKER_VERSION}/binary-client/docker* bundles/${DOCKER_VERSION}/binary-daemon/docker* dist/docker

cd dist
tar --exclude='*.md5' --exclude='*.sha256' --exclude="*-${DOCKER_VERSION}" \
       -czvf docker-v${DOCKER_VERSION}_${ARCH}.tgz \
       docker/*
